security:
  whiteList:
    - "/kanban/entrance"
    - "/kanban/publicKey"
    - "/kanban/registration"
    - "/kanban/login"
    - "/kanban/passwordRetrievalApplication"
    - "/kanban/{userName}/passwordResetApplication"
    - "/kanban/{userName}/password"
    - "/kanban/unauthorised"
    - "/kanban/error"
    - "/kanban/index.html"
    - "/kanban/favicon.ico"
    - "/kanban/js/{}"
    - "/kanban/css/{}"
    - "/kanban/fonts/{}"
    - "/kanban/img/{}"
    - "/kanban/component/{}"
    - "/kanban/foundation/{}"
  allowedOrigins:
    - "http://localhost:9120"
    - "http://127.0.0.1:8008"
    - "http://23.234.54.252:8089"
    - "http://www.thiki.org"



